# Generated by Django 4.1.3 on 2022-11-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_transfer_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transfer_hour",
            field=models.TimeField(),
        ),
    ]
